[General]
network = SmartCityNetwork
sim-time-limit = 100s

# Server auf srv2
*.srv2.numApps = 1
*.srv2.app[0].typename = "TcpGenericServerApp"
*.srv2.app[0].localPort = 1000

# Client auf cli1
*.cli1.numApps = 1
*.cli1.app[0].typename = "TelnetApp"
*.cli1.app[0].connectAddress = "srv2"
*.cli1.app[0].connectPort = 1000
*.cli1.app[0].startTime = 1s